name: Debug Workflow

on:
  push:
    branches:
      - main

jobs:
  debug-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print directory structure
      run: |
        pwd
        ls -R

    - name: Verify my-website folder
      run: |
        cd my-website
        ls
